POST http://localhost:3000/v1/categories
content-type: application/json

{
  "name": "Category Name"
}

###
GET http://localhost:3000/v1/categories

###
GET http://localhost:3000/v1/categories/b9406a79-f3c9-4465-bb93-8936fdf14779

### 
PUT http://localhost:3000/v1/categories/b9406a79-f3c9-4465-bb93-8936fdf14779
Content-Type: application/json

{
  "name": "Updated Category Name"
}

###
DELETE http://localhost:3000/v1/categories/b9406a79-f3c9-4465-bb93-8936fdf14779