version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: media-education-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=media-education
