services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: edutrain-dev-db
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=edutrain
      - POSTGRES_PASSWORD=EdutrainDev
      - POSTGRES_DB=edutrain_db
    volumes:
      - /root/backup/dev:/home/backup

  postgres-prod:
    image: postgres:16-alpine
    container_name: edutrain-prod-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=edutrain
      - POSTGRES_PASSWORD=EdutrainProd
      - POSTGRES_DB=edutrain_db
    volumes:
      - /root/backup/prod:/home/backup

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5050:80"
